title = "HLState"

# Bind server on given host
host = "::1"

# Bind server on given port
port = 8027

# Configure instance in the debug mode
debug = true

# Path to `xash3d-query` bin
query = "xash3d-query"

# Define at least one master to scrape game servers from
masters = ["[202:68d0:f0d5:b88d:1d1a:555e:2f6b:3148]:27010", "[300:dee4:d3c0:953b::2019]:27010"]